using System.CommandLine;

namespace Agibuild.Fulora.Cli.Commands;

internal static class AddCommand
{
    internal static Command Create()
    {
        var nameArg = new Argument<string>("name") { Description = "Service name (PascalCase, e.g. UserService)" };
        var importOpt = new Option<bool>("--import")
        {
            Description = "Generate a [JsImport] interface (C#→JS) instead of [JsExport] (JS→C#)"
        };

        var serviceCmd = new Command("service", "Scaffold a new bridge service (interface + implementation + TS proxy)")
        {
            nameArg,
            importOpt
        };

        serviceCmd.SetAction((parseResult, _) =>
        {
            var name = parseResult.GetValue(nameArg)!;
            var isImport = parseResult.GetValue(importOpt);
            var bridgeDir = DetectBridgeProjectDir();
            var webDir = DetectWebSrcDir();

            if (bridgeDir is null)
            {
                Console.Error.WriteLine("Could not find a Bridge project directory.");
                return Task.CompletedTask;
            }

            var interfaceName = name.StartsWith('I') ? name : $"I{name}";
            var className = interfaceName[1..];
            var attr = isImport ? "[JsImport]" : "[JsExport]";

            var ns = DetectNamespace(bridgeDir);
            var servicesDir = Path.Combine(bridgeDir, "Services");
            Directory.CreateDirectory(servicesDir);

            var interfaceFile = Path.Combine(servicesDir, $"{interfaceName}.cs");
            if (!File.Exists(interfaceFile))
            {
                File.WriteAllText(interfaceFile, $$"""
                    using Agibuild.Fulora;

                    namespace {{ns}};

                    {{attr}}
                    public interface {{interfaceName}}
                    {
                        Task<string> GetStatus();
                    }
                    """);
                Console.WriteLine($"  Created {Path.GetRelativePath(Directory.GetCurrentDirectory(), interfaceFile)}");
            }

            if (!isImport)
            {
                var implFile = Path.Combine(servicesDir, $"{className}.cs");
                if (!File.Exists(implFile))
                {
                    File.WriteAllText(implFile, $$"""
                        namespace {{ns}};

                        public class {{className}} : {{interfaceName}}
                        {
                            public Task<string> GetStatus() => Task.FromResult("OK");
                        }
                        """);
                    Console.WriteLine($"  Created {Path.GetRelativePath(Directory.GetCurrentDirectory(), implFile)}");
                }
            }

            if (webDir is not null)
            {
                var bridgeTsDir = Path.Combine(webDir, "bridge");
                Directory.CreateDirectory(bridgeTsDir);

                var camelName = char.ToLowerInvariant(className[0]) + className[1..];
                var tsFile = Path.Combine(bridgeTsDir, $"{camelName}.ts");
                if (!File.Exists(tsFile))
                {
                    var content = isImport
                        ? $$"""
                            // {{interfaceName}} — JS implementation for C# [JsImport] proxy
                            export const {{camelName}} = {
                              getStatus: async (): Promise<string> => {
                                return 'OK';
                              },
                            };
                            """
                        : $$"""
                            // {{interfaceName}} — TypeScript client for C# [JsExport] service
                            // Types are auto-generated by Bridge.Generator at build time.
                            // This file provides a convenience re-export.
                            import { bridgeClient } from './services';

                            export const {{camelName}} = bridgeClient<{
                              getStatus(): Promise<string>;
                            }>('{{className}}');
                            """;
                    File.WriteAllText(tsFile, content);
                    Console.WriteLine($"  Created {Path.GetRelativePath(Directory.GetCurrentDirectory(), tsFile)}");
                }
            }

            Console.WriteLine($"Service '{className}' scaffolded successfully.");
            return Task.CompletedTask;
        });

        var cmd = new Command("add", "Scaffold new components") { serviceCmd };
        return cmd;
    }

    private static string? DetectBridgeProjectDir()
    {
        var dir = Directory.GetCurrentDirectory();
        var bridgeProjects = Directory.GetFiles(dir, "*.Bridge.csproj", SearchOption.AllDirectories);
        return bridgeProjects.Length >= 1 ? Path.GetDirectoryName(bridgeProjects[0]) : null;
    }

    private static string? DetectWebSrcDir()
    {
        var dir = Directory.GetCurrentDirectory();
        var packageJsonFiles = Directory.GetFiles(dir, "package.json", SearchOption.AllDirectories)
            .Where(f => !f.Contains("node_modules") && !f.Contains("packages"))
            .ToArray();

        foreach (var pj in packageJsonFiles)
        {
            var srcDir = Path.Combine(Path.GetDirectoryName(pj)!, "src");
            if (Directory.Exists(srcDir)) return srcDir;
        }
        return null;
    }

    private static string DetectNamespace(string bridgeDir)
    {
        var csproj = Directory.GetFiles(bridgeDir, "*.csproj").FirstOrDefault();
        if (csproj is not null)
        {
            var name = Path.GetFileNameWithoutExtension(csproj);
            return name;
        }
        return "MyApp.Bridge";
    }
}
